version: '2'
services:
  frontend:
    build: frontend
    ports:
      - "80"
    links:
      - backend
  backend:
    build: backend
    ports:
      - "8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - UNTAPPD_CLIENT_ID
      - UNTAPPD_CLIENT_SECRET
      - PG_CONNECTION_STRING=postgres://oispa:kaljaa@database/oispa_db
    links:
      - database
  database:
    image: postgres:9.6.2-alpine
    environment:
      - POSTGRES_DB=oispa_db
      - POSTGRES_USER=oispa
      - POSTGRESS_PASSWORD=kaljaa
