service: oispa

frameworkVersion: ">=1.6.1"

plugins:
  - serverless-webpack

custom:
  region: eu-west-1
  s3BucketName: oispa

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ${self:custom.region}
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:custom.region}:*:*"

functions:
  beerstylesGet:
    handler: handlers/beerstyles.get
  beerstylesUpdate:
    handler: handlers/beerstyles.update
    timeout: 10

resources:
  Resources:
    BeerstylesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Beerstyles
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    FrontendS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    FrontendS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: FrontendS3Bucket
        PolicyDocument:
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::${self:custom.s3BucketName}/*
              Principal: "*"
