service: oispa

frameworkVersion: ">=1.6.1"

plugins:
  - serverless-webpack

custom:
  region: eu-west-1

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ${self:custom.region}
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:custom.region}:*:*"

functions:
  beerstylesGet:
    handler: handlers/beerstyles.get
  beerstylesUpdate:
    handler: handlers/beerstyles.update
    timeout: 10

resources:
  Resources:
    beerstylesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Beerstyles
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
